### ISSUE TITLE
How to interpret the trajectories

### ISSUE THREAD

**Issue by soerenab** [lacava/ode-strogatz#1]
Dear @lacava , Thank you very much for setting this repository! 

I am wondering how I have to interpret the txt files that contain the trajectories of every problem. Each file seems to have three columns, and the first row denotes them as `label,x,y`. I am guessing that one of the columns is the independent variable of each problem (e.g. time) whereas the other two columns correspond to the two variables of each system. Which column is what though?

I have plotted the three trajectories of `d_bacres1.txt` below:

![d_bacres1](https://user-images.githubusercontent.com/36963673/147856994-bf4333aa-84a5-4fe5-95ed-351ef6423add.png)

I am guessing that each trajectory contains 4 separate simulations (each with 100 steps), which are simply concatenated in the file? The simulation steps correspond to the x axes in the figure above. But what do the y-axes correspond to?

Thanks you very much for any help!

**Comment by B0Gec** [comment]
I recommend you to look into matlab file [`simulate_ode.m`](https://github.com/lacava/ode-strogatz/blob/master/simulate_ode.m#L14) to see how those files are generated. 

From
```matlab
bacres1((i-1)*n+1:i*n,:) = [df_s(1:n) f_s(1:n) y_s(1:n)]; 
```
I conclude that column _label_ there means values of derivative \dot{x} of first state variable x, and _x_ and _y_ represent state variable values.

**Comment by lacava** [comment]
@B0Gec is correct.
