### ISSUE TITLE
Which integration method was used?

### ISSUE THREAD

**Issue by NinaOmejc** [lacava/ode-strogatz#2]
Tnx for the benchmark (I have seen it's also going to be used in SR competition). We would like to use this benchmark but have some difficulties. We are running our symbolic regression method in python, where we evaluate the reconstructed model also by trajectory error. For that we need true trajectory and a model trajectory, to calculate the difference. The problem is, we can't replicate true trajectories using pythonic solve_ivp method (have tried "LSODA",  "RK4", BS45 and BS45_i, the last two are Bogacki-Shampine algorithms) but none of them produces the same trajectories as are yours. Some of the trajectories are the same of course, but some are completely off. In the figure attached, I present two such cases. The question we have is, consequently, which algorithm did you use to numerically integrate the system functions, so we can use the same algorithm for our reconstructed models and thus correctly compare our method for system identification. Thank you! 

![comparison](https://user-images.githubusercontent.com/48597559/211043589-dfaa0ac6-dbeb-4dcd-94c4-60c130af1f4e.png)

**Comment by lacava** [comment]
Hi @NinaOmejc , the full details are in the Simulink model: https://github.com/lacava/ode-strogatz/blob/master/physic_mods_2state.mdl . This was simulated in Matlab/Simulink using "ode3" (Bogacki-Shampine). You might consult that documentation to see if there are differences. Let me know if you run into any other issues.
